#include <iostream>
#include <cassert>
#include "string.hpp"

int main() {
    {
        //------------------------------------------------------
        // SETUP FIXTURE

        // TEST
        String str("0fuuuuhfugguhuhrfgug4uwu");

        // VERIFY
        assert(str == "0fuuuuhfugguhuhrfgug4uwu");
    }

    {
        //------------------------------------------------------
        // SETUP FIXTURE

        // TEST
        String str("Anjefjeqjeifjieiffneeiwfifijw");

        // VERIFY
        assert(str == "Anjefjeqjeifjieiffneeiwfifijw");
    }

    {
        //------------------------------------------------------
        // SETUP FIXTURE

        // TEST
        String str("zRWBGRSFGBDGREGREG");

        // VERIFY
        assert(str == "zRWBGRSFGBDGREGREG");
    }

    {
        //------------------------------------------------------
        // SETUP FIXTURE

        // TEST
        String str("!JEWIJRIQJRIJWIjIJFIDGEWJFIJFIDJFIEJIJWIJIFJIDSFJQWIJFIGJEEFIFDJFEKDJAKSDJAWJIWJEIFJEIFIEJFEIFJIEE");

        // VERIFY
        assert(str == "!JEWIJRIQJRIJWIjIJFIDGEWJFIJFIDJFIEJIJWIJIFJIDSFJQWIJFIGJEEFIFDJFEKDJAKSDJAWJIWJEIFJEIFIEJFEIFJIEE");
    }

    {
        //------------------------------------------------------
        // SETUP FIXTURE

        // TEST
        String str("%JJEIRJQWIJFEWFRFIWEJFVFGEGNWEFEWIBUFHFNEUFEUFBEUFEJFEFUEBEUUENEUEUBEUBEFBEFUBSFUEBFUEBFUBEUBEUBJADBUDAJWDNUEEUNFENDUDFUENFUEFUEBBWBFBEFBUJENFBUJWDNUANSJNDJADNJWDWUDWUWUBUBBWD");

        // VERIFY
        assert(str == "%JJEIRJQWIJFEWFRFIWEJFVFGEGNWEFEWIBUFHFNEUFEUFBEUFEJFEFUEBEUUENEUEUBEUBEFBEFUBSFUEBFUEBFUBEUBEUBJADBUDAJWDNUEEUNFENDUDFUENFUEFUEBBWBFBEFBUJENFBUJWDNUANSJNDJADNJWDWUDWUWUBUBBWD");
    }

    {
        //------------------------------------------------------
        // SETUP FIXTURE

        // TEST
        String str("jdjifjiewfnijeijdfwqijejfijifweifewfeffjiwjengDJEJDIJEWJEIWJWEFEHIEHFviwekfnknewifneifngiewnriwekrnqjwruqejNJRFNWQHEJJJEFBWEKFERURJWEFUIWFBEUQBWFEBFEUEJFEJFBENJWQREJGFBUEQRFWQURUEFUEFUBEBUWQRQWURBUWQB");

        // VERIFY
        assert(str == "jdjifjiewfnijeijdfwqijejfijifweifewfeffjiwjengDJEJDIJEWJEIWJWEFEHIEHFviwekfnknewifneifngiewnriwekrnqjwruqejNJRFNWQHEJJJEFBWEKFERURJWEFUIWFBEUQBWFEBFEUEJFEJFBENJWQREJGFBUEQRFWQURUEFUEFUBEBUWQRQWURBUWQB");
    }

    {
        //------------------------------------------------------
        // SETUP FIXTURE

        // TEST
        String str("Xeurihughuwehruhrwuerhfuhurfirh3rhehrheh3hqrguhehuhruehuwehrufefherfuqrhuehruqhruehruhruefhurhuqehfuhuwehufhw3QWFHU3QHU3QHRRHURURH8WQRHQHRWRHFHUHRQ38RQ");

        // VERIFY
        assert(str == "Xeurihughuwehruhrwuerhfuhurfirh3rhehrheh3hqrguhehuhruehuwehrufefherfuqrhuehruqhruehruhruefhurhuqehfuhuwehufhw3QWFHU3QHU3QHRRHURURH8WQRHQHRWRHFHUHRQ38RQ");
    }
    {
        //------------------------------------------------------
        // SETUP FIXTURE

        // TEST
        String str("HFJAHDSJFHSJDAHFEWIFHSJFIHEFJHDSJFHIFHWEIAFJSDHFJAHDFJHAJDSHFJEHHFAJHEURHFIFHJFHWEIFEWIFEWHEUFHFIUWEHFIRHFUIQFHUWEFHWFHIUWEHFHEFIFEHFEWHIFHWEUIHFWEUIFHIEWUFHUHFEHFEWFUIQWEHFIUEWHFWHIFUHIUEWHFUIEHFHEIFUFHEUIFHEUIRHUIEWHRUIEHFUIEWHRUEHRUEHRUIQWEHEHWFEWIEUWHEFIHUWEFHIUEWHFUHRWIFRUWHFEWIHRFIUEWFRHUEWIHRUEHRHRIUWHEFUEIWUHFIEWEHWIFUIWHFUEHFIWUEHFIUEWHFUIWRHFUIQHUWEFHUEWQHWEUFHEWHUEHUWFUWEHFUHWQFHWEUHFUWEIQWEUDUFHEUQIFHUIEWQFHUEFIWEUQIUEWFHDUSHFUIWEUEWFUEIWHFEUFHIUQWEFHIWHUFHUWEFHUEWIUFUEWHERHUERHIWEQHUFRHIUQWFHUWEHUDFHIUWEFUIWEHUEHIUIWEQURH");

        // VERIFY
        assert(str == "HFJAHDSJFHSJDAHFEWIFHSJFIHEFJHDSJFHIFHWEIAFJSDHFJAHDFJHAJDSHFJEHHFAJHEURHFIFHJFHWEIFEWIFEWHEUFHFIUWEHFIRHFUIQFHUWEFHWFHIUWEHFHEFIFEHFEWHIFHWEUIHFWEUIFHIEWUFHUHFEHFEWFUIQWEHFIUEWHFWHIFUHIUEWHFUIEHFHEIFUFHEUIFHEUIRHUIEWHRUIEHFUIEWHRUEHRUEHRUIQWEHEHWFEWIEUWHEFIHUWEFHIUEWHFUHRWIFRUWHFEWIHRFIUEWFRHUEWIHRUEHRHRIUWHEFUEIWUHFIEWEHWIFUIWHFUEHFIWUEHFIUEWHFUIWRHFUIQHUWEFHUEWQHWEUFHEWHUEHUWFUWEHFUHWQFHWEUHFUWEIQWEUDUFHEUQIFHUIEWQFHUEFIWEUQIUEWFHDUSHFUIWEUEWFUEIWHFEUFHIUQWEFHIWHUFHUWEFHUEWIUFUEWHERHUERHIWEQHUFRHIUQWFHUWEHUDFHIUWEFUIWEHUEHIUIWEQURH");
    }
    {
        //------------------------------------------------------
        // SETUP FIXTURE

        // TEST
        String str("IIWJFIWEJIJEIDJEWIJDKSJIWEIJIWERIEWIEWJFIEJFWEHFWIEFHEUIFHIWEHWHUEHFHDSJAHFWEUIFHIEWHFUWEHFUIWEHRFUEWHRWUEFHWEHUFWUFHEHEIUHAUHEUWEHEAHUFEWUUFUEWFHUEWFHUWEFUWHAUSDHAFEHUFHUQWUEWFHEWUFHUEWHFUEWUFHWUQFUWEHFIUEWQHFUEWFUHQUWIEQHFUEHUWEUFHEWFHUWEHFWEIFEIWUFWHIEFEHWFUEWFHUIWEHFHEWFHEIWUFUWEHFUFRIHFHWEHUHFWEHFUWIEHFHWEIHFWEURFURFQHFEEUUFWHFIHWEFURUFUHUHFEIUERUUWHWEIFEUFHUIWEHRUHRUUIFHUEWHFRUFUHIEWHFUHWEURUEWHRIUEFHEUWRHEWUFUEWUHRUWERUEHRUIFHUEWIFURWEUFWHURHRWUUHFUWUFHRHHRFUUHFRWUIWRHUWRIIWQEURFHIWUFHUIWUHURUWIRHURWFIRFHURIFUWQURRIQWRUQIUFRUIRFURUFRIQFUFHIRWQHIUFHQIWH");

        // VERIFY
        assert(str == "IIWJFIWEJIJEIDJEWIJDKSJIWEIJIWERIEWIEWJFIEJFWEHFWIEFHEUIFHIWEHWHUEHFHDSJAHFWEUIFHIEWHFUWEHFUIWEHRFUEWHRWUEFHWEHUFWUFHEHEIUHAUHEUWEHEAHUFEWUUFUEWFHUEWFHUWEFUWHAUSDHAFEHUFHUQWUEWFHEWUFHUEWHFUEWUFHWUQFUWEHFIUEWQHFUEWFUHQUWIEQHFUEHUWEUFHEWFHUWEHFWEIFEIWUFWHIEFEHWFUEWFHUIWEHFHEWFHEIWUFUWEHFUFRIHFHWEHUHFWEHFUWIEHFHWEIHFWEURFURFQHFEEUUFWHFIHWEFURUFUHUHFEIUERUUWHWEIFEUFHUIWEHRUHRUUIFHUEWHFRUFUHIEWHFUHWEURUEWHRIUEFHEUWRHEWUFUEWUHRUWERUEHRUIFHUEWIFURWEUFWHURHRWUUHFUWUFHRHHRFUUHFRWUIWRHUWRIIWQEURFHIWUFHUIWUHURUWIRHURWFIRFHURIFUWQURRIQWRUQIUFRUIRFURUFRIQFUFHIRWQHIUFHQIWH");
    }{
        //------------------------------------------------------
        // SETUP FIXTURE

        // TEST
        String str("UUEUEUHDUHUWHFUWHEEWUHUEUWUWHUEHUEWHDEWUHUEWHFUHWEFUHFWEU7HFJAHDSJFHSJDAHFEWIFHSJFIHEFJHDSJFHIFHWEIAFJSDHFJAHDFJHAJDSHFJEHHFAJHEURHFIFHJFHWEIFEWIFEWHEUFHFIUWEHFIRHFUIQFHUWEFHWFHIUWEHFHEFIFEHFEWHIFHWEUIHFWEUIFHIEWUFHUHFEHFEWFUIQWEHFIUEWHFWHIFUHIUEWHFUIEHFHEIFUFHEUIFHEUIRHUIEWHRUIEHFUIEWHRUEHRUEHRUIQWEHEHWFEWIEUWHEFIHUWEFHIUEWHFUHRWIFRUWHFEWIHRFIUEWFRHUEWIHRUEHRHRIUWHEFUEIWUHFIEWEHWIFUIWHFUEHFIWUEHFIUEWHFUIWRHFUIQHUWEFHUEWQHWEUFHEWHUEHUWFUWEHFUHWQFHWEUHFUWEIQWEUDUFHEUQIFHUIEWQFHUEFIWEUQIUEWFHDUSHFUIWEUEWFUEIWHFEUFHIUQWEFHIWHUFHUWEFHUEWIUFUEWHERHUERHIWEQHUFRHIUQWFHUWEHUDFHIUWEFUIWEHUEHIUIWEQURH");

        // VERIFY
        assert(str == "UUEUEUHDUHUWHFUWHEEWUHUEUWUWHUEHUEWHDEWUHUEWHFUHWEFUHFWEU7HFJAHDSJFHSJDAHFEWIFHSJFIHEFJHDSJFHIFHWEIAFJSDHFJAHDFJHAJDSHFJEHHFAJHEURHFIFHJFHWEIFEWIFEWHEUFHFIUWEHFIRHFUIQFHUWEFHWFHIUWEHFHEFIFEHFEWHIFHWEUIHFWEUIFHIEWUFHUHFEHFEWFUIQWEHFIUEWHFWHIFUHIUEWHFUIEHFHEIFUFHEUIFHEUIRHUIEWHRUIEHFUIEWHRUEHRUEHRUIQWEHEHWFEWIEUWHEFIHUWEFHIUEWHFUHRWIFRUWHFEWIHRFIUEWFRHUEWIHRUEHRHRIUWHEFUEIWUHFIEWEHWIFUIWHFUEHFIWUEHFIUEWHFUIWRHFUIQHUWEFHUEWQHWEUFHEWHUEHUWFUWEHFUHWQFHWEUHFUWEIQWEUDUFHEUQIFHUIEWQFHUEFIWEUQIUEWFHDUSHFUIWEUEWFUEIWHFEUFHIUQWEFHIWHUFHUWEFHUEWIUFUEWHERHUERHIWEQHUFRHIUQWFHUWEHUDFHIUWEFUIWEHUEHIUIWEQURH");
    }{
        //------------------------------------------------------
        // SETUP FIXTURE

        // TEST
        String str("DSUFHUWHFUWEHFJKDFASDHFJAIJFHIWUFHUFHUWEHFUEWFUIEWHFW8HFJAHDSJFHSJDAHFEWIFHSJFIHEFJHDSJFHIFHWEIAFJSDHFJAHDFJHAJDSHFJEHHFAJHEURHFIFHJFHWEIFEWIFEWHEUFHFIUWEHFIRHFUIQFHUWEFHWFHIUWEHFHEFIFEHFEWHIFHWEUIHFWEUIFHIEWUFHUHFEHFEWFUIQWEHFIUEWHFWHIFUHIUEWHFUIEHFHEIFUFHEUIFHEUIRHUIEWHRUIEHFUIEWHRUEHRUEHRUIQWEHEHWFEWIEUWHEFIHUWEFHIUEWHFUHRWIFRUWHFEWIHRFIUEWFRHUEWIHRUEHRHRIUWHEFUEIWUHFIEWEHWIFUIWHFUEHFIWUEHFIUEWHFUIWRHFUIQHUWEFHUEWQHWEUFHEWHUEHUWFUWEHFUHWQFHWEUHFUWEIQWEUDUFHEUQIFHUIEWQFHUEFIWEUQIUEWFHDUSHFUIWEUEWFUEIWHFEUFHIUQWEFHIWHUFHUWEFHUEWIUFUEWHERHUERHIWEQHUFRHIUQWFHUWEHUDFHIUWEFUIWEHUEHIUIWEQURH");

        // VERIFY
        assert(str == "DSUFHUWHFUWEHFJKDFASDHFJAIJFHIWUFHUFHUWEHFUEWFUIEWHFW8HFJAHDSJFHSJDAHFEWIFHSJFIHEFJHDSJFHIFHWEIAFJSDHFJAHDFJHAJDSHFJEHHFAJHEURHFIFHJFHWEIFEWIFEWHEUFHFIUWEHFIRHFUIQFHUWEFHWFHIUWEHFHEFIFEHFEWHIFHWEUIHFWEUIFHIEWUFHUHFEHFEWFUIQWEHFIUEWHFWHIFUHIUEWHFUIEHFHEIFUFHEUIFHEUIRHUIEWHRUIEHFUIEWHRUEHRUEHRUIQWEHEHWFEWIEUWHEFIHUWEFHIUEWHFUHRWIFRUWHFEWIHRFIUEWFRHUEWIHRUEHRHRIUWHEFUEIWUHFIEWEHWIFUIWHFUEHFIWUEHFIUEWHFUIWRHFUIQHUWEFHUEWQHWEUFHEWHUEHUWFUWEHFUHWQFHWEUHFUWEIQWEUDUFHEUQIFHUIEWQFHUEFIWEUQIUEWFHDUSHFUIWEUEWFUEIWHFEUFHIUQWEFHIWHUFHUWEFHUEWIUFUEWHERHUERHIWEQHUFRHIUQWFHUWEHUDFHIUWEFUIWEHUEHIUIWEQURH");
    }

    std::cout << "Done testing single character constructor." << std::endl;
    return 0;
}